const UserActionType = {
  GET_FORMS: "GET_FORMS",
  CREATE_FORMS: "CREATE_FORMS",
  GET_FORM: "GET_FORM",
  SUBMIT_RESPONSE: "SUBMIT_RESPONSE",
  GET_RESPONSE: "GET_RESPONSE",
};

export default UserActionType;
